{% set name = "splink" %}
{% set version = "3.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c9a9dc2e50048dcac071d3445211c2d3d38d45a28e4c9ec1b99d3e4264ba80dd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - poetry >=0.12
  run:
    - python >=3.8,<4.0
    - jsonschema >=3.2,<5.0
    - python-duckdb >=0.8.0
    - pandas >=1.2.0
    - sqlglot >=7.0.0
    - altair >=5.0.1,<6.0
    - jinja2 >=3.0.3,<4.0.0
  run_constrained:
    - pyspark >=3.2.1
    - sqlalchemy >=1.4.0,<2.0.0

test:
  imports:
    - splink

about:
  home: https://github.com/moj-analytical-services/splink
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast, accurate and scalable probabilistic data linkage using your choice of SQL backend.
  doc_url: https://moj-analytical-services.github.io/splink/

extra:
  recipe-maintainers:
    - ThomasHepworth
    - ADBond
    - cdesouza21
