{% set name = "splink" %}
{% set version = "4.0.12" %}
{% set python_min = python_min|default("3.8") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 66a7a08e354d174cc9f126a74f3811080804fbc774506952fe618dad80f1900a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - python-duckdb >=0.9.2
    - pandas >=1.3.5
    - sqlglot >=17.6.0
    - altair >=5.0.1
    - jinja2 >=3.0.3
    - numpy >=1.17.3
    - python-igraph >=0.11.2
  run_constrained:
    - pyspark >=3.5.0
    - sqlalchemy >=1.4.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - splink
  commands:
    - pip check

about:
  home: https://github.com/moj-analytical-services/splink
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast, accurate and scalable probabilistic data linkage using your choice of SQL backend.
  doc_url: https://moj-analytical-services.github.io/splink/

extra:
  recipe-maintainers:
    - ThomasHepworth
    - ADBond
    - cdesouza21
